#define		INTERCEPTION_FUNCNUM						4
#define		INTERCEPTION_FUNC_FILESCAN				0
#define		INTERCEPTION_FUNC_REGSCAN				1
#define		INTERCEPTION_FUNC_OPENPROCESS		2
#define		INTERCEPTION_FUNC_CREATEPROCESS	3

typedef struct _DATA_QDSYSCFG
{
	BOOL	bInterception[INTERCEPTION_FUNCNUM];
}QDSYSTEMCONFIG, *PQDSYSTEMCONFIG;

typedef struct _DATA_QDSYSMGR
{
	BOOL	bProtection;
	BOOL	bStartup;
}QDSYSTEMMANAGE, *PQDSYSTEMMANAGE;

typedef struct _DATA_QDSYSINFO
{
	HINSTANCE	hSysInstance;
}QDSYSTEMINFO, *PQDSYSTEMINFO;

typedef struct _SYSTEM_GLOBAL_INFO
{
	QDSYSTEMCONFIG		SystemConfig;
	QDSYSTEMMANAGE	SystemManage;
	QDSYSTEMINFO			SystemInfo;
}QDSYSGLOBALINFO, *PQDSYSTEMGLOBALINFO;

